name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  setup-npmrc:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.16.0]
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: echo "registry=https://registry.yarnpkg.com/" > .npmrc
      - run: echo "@internxt:registry=https://npm.pkg.github.com" >> .npmrc
      - run: echo //npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }} >> .npmrc
      - run: echo "always-auth=true" >> .npmrc
  
  unit-tests:
    uses: oclif/github-workflows/.github/workflows/unitTest.yml@main
